articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',                                   views.ArticleListView.as_view(), name='list'),
    path('new',                                views.ArticleCreateView.as_view(),  name='new'),
    path('pages/<slug:slug>',                  views.PageView.as_view(), name='page-view'),
    path('pages/',                            views.PageListView.as_view(), name='page-view'),
    path('images/',                           views.ArticleImageListView.as_view(), name='image-list'),
    path('images/new',                        views.ArticleImageCreateView.as_view(), name='image-new'),
    path('images/<int:pk>',             views.ArticleImageView.as_view(), name='image-view'),
    path('images/<int:pk>/edit',        views.ArticleImageUpdateView.as_view(), name='image-edit'),
    path('images/<int:pk>/delete',      views.ArticleImageDeleteView.as_view(), name='image-delete'),

    path('tags/<slug:slug>',        views.ArticleTagView.as_view(), name='tag-view'),

    path('<slug:slug>',             views.ArticleView.as_view(), name='view'),
    path('<slug:slug>/edit',        views.ArticleUpdateView.as_view(), name='edit'),
    path('<slug:slug>/delete',      views.ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from articles.views import PageView, HomePageView, PageListView
admin.autodiscover()

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),

    # Authentication
    # url('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # path('articles/', include('articles.urls')),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url('admin/doc/', include('django.contrib.admindocs.urls')),
    path('search', include(('search.urls', 'search'), namespace='search')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    path('pages/', PageListView.as_view(), name='page-list-view'),
    path('<slug:slug>', PageView.as_view(), name='page-view'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

articles/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.urls import reverse
from django.utils.text import slugify
from django import forms
from django.core.cache import caches
from django.db.models.signals import post_save, post_delete

cache = caches['default']


class ArticleTag(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=50, blank=False, unique=True)

    class Meta:
        app_label = 'articles'

    def __str__(self):
        return self.title

    def clean(self):
        self.slug = slugify(self.title)

class Article(models.Model):
    # author
    author = models.ForeignKey(User, editable=False, on_delete=models.SET_NULL, null=True)
    # title
    title = models.CharField(max_length=100)
    subheading = models.CharField(max_length=100, blank=True)
    # body
    body = models.TextField()
    # image
    image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)

    slug = models.SlugField(max_length=50, blank=True, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    pub_date = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)
    is_page = models.BooleanField(default=False)
    tags = models.ManyToManyField(ArticleTag, blank=True)

    class Meta:
        app_label = 'articles'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        if self.is_page:
            return reverse('page-view', args=[self.slug])
        else:
            return reverse('articles:view', args=[self.slug])

    def clean(self):
        # Set the pub_date for published items if it hasn't been set already.
        if self.published and self.pub_date is None:
            self.pub_date = datetime.date.today()

        if self.slug == "":
            self.slug = slugify(self.title)

class ArticleAdmin(admin.ModelAdmin):
    prepopulated_fields = {"slug" : ("title",)}

class ArticleImage(models.Model):
    article = models.ForeignKey(Article, related_name='images', on_delete=models.CASCADE)
    # title
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    # image
    image = models.ImageField(upload_to='articles/%Y/%m/%d')

    class Meta:
        app_label = 'articles'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:image-view', args=[self.pk])


# from .models import Article

def menu_for_pages(request):
    '''
    Provides a list of static pages for the menu
    '''
    data = cache.get('menu_for_pages')
    if data is None:
        data = {
            'menu_pages': Article.objects.filter(published=True).filter(is_page=True).exclude(slug__in=['home','articles'])
        }
        cache.set('menu_for_pages', data, 300)
    return data

def articles_changed(sender, **kwargs):
    '''
    Flushes the page cache when a page is saved
    '''
    instance = kwargs['instance']
    if instance.published and instance.is_page and instance.slug not in ['home', 'articles']:
        cache.delete('menu_for_pages')

post_save.connect(articles_changed, sender=Article)
post_delete.connect(articles_changed, sender=Article)

articles/forms.py
from django import forms
from .models import Article, ArticleImage

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title','body','subheading', 'image', 'slug', 'published', 'is_page')

class ArticleImageForm(forms.ModelForm):
    class Meta:
        model = ArticleImage
        fields = ('title', 'image')

articles/views.py
import re
import logging

# Create your views here.
from django import forms
from django.utils.text import slugify
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, PageNotAnInteger
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.decorators.cache import cache_page, never_cache
from django.template import RequestContext, loader
from django.db.models import Count
from django.forms import ModelForm

from django.core.cache import caches

from django.utils.text import slugify
from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView, FormView
from django.utils import timezone
from django.conf import settings
from django.forms.formsets import formset_factory
from django.forms.models import modelform_factory

from braces.views import LoginRequiredMixin

from articles.forms import ArticleForm, ArticleImageForm
from articles.models import Article, ArticleImage, ArticleTag

logger = logging.getLogger(__name__)

cache = caches['default']

def _get_images_in_text(text):
    m = re.findall(r"\{image:(?P<image_number>\d+)\}", text)
    ret = []
    for number in m:
        ret.append(int(number))
    return ret

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'subheading', 'body', 'image', 'slug', 'published', 'is_page')

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)

        if self.instance.pk:
            tags = ", ".join([x.title for x in self.instance.tags.all()])
        else:
            tags = ""
        self.fields['tags_text'] = forms.CharField(label="Tags", required=False, initial=tags)

    def clean_tags_text(self):
        raw = self.cleaned_data['tags_text']

        csv = []
        for tag in raw.split(','):
            if len(tag.strip()) > 0:
                csv.append(tag.strip())

        # Deduplicate
        self.cleaned_data['tags_text'] = list(set(csv))
        return self.cleaned_data['tags_text']

    def save(self, force_insert=False, force_update=False, commit=True):
        article = super(ArticleForm, self).save(commit=True)  # have to save to access article.tags

        # Get the tags we want
        tags_text_list = self.cleaned_data['tags_text']

        # See which ones exist
        tags = ArticleTag.objects.filter(title__in=tags_text_list)

        # Start from scratch
        article.tags.clear()

        # Add existing tags
        for tag in tags:
            article.tags.add(tag.pk)

        # Create new ones
        for tag in tags_text_list:
            if tag not in [t.title for t in tags]:
                # Create tag
                article.tags.create(title=tag, slug=slugify(tag))

        if commit:
            article.save()
        return article

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articles/article_form.html'

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO, 'Article saved')
        form.instance.author = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = 'articles/article_form.html'
    form_class = ArticleForm
    # fields = ['title', 'subheading', 'body','image','slug','published','is_page', 'tags']
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleUpdateView, self).get_context_data(**kwargs)
        context['header_image'] = context[self.context_object_name].image
        return context

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO, 'Article updated')
        return super(ArticleUpdateView, self).form_valid(form)

class ArticleView(DetailView):
    template_name = 'articles/article.html'
    model = Article
    context_object_name = 'article'

    def get_queryset(self):
        queryset = super(ArticleView, self).get_queryset()

        if not self.request.user.is_authenticated:
            queryset = queryset.filter(published=True)

        return queryset.filter(is_page=False)

    def get_context_data(self, **kwargs):
        context = super(ArticleView, self).get_context_data( **kwargs)
        image_ids = _get_images_in_text(context[self.context_object_name].body)
        if len(image_ids) > 0:
            objs = ArticleImage.objects.filter(pk__in=image_ids)
            images = {}
            for i in objs:
                images[i.pk] = i

        body = context[self.context_object_name].body
        for i in image_ids:
            body = body.replace('{image:%d}' % i, '![%s](%s)' % (images[i].title, images[i].image.url))

        context['body'] = body
        context['header_image'] = context[self.context_object_name].image
        return context

class PageView(DetailView):
    template_name = 'articles/page.html'
    model = Article
    context_object_name = 'page'

    def get_queryset(self):
        queryset = super(PageView, self).get_queryset()

        return queryset.filter(is_page=True).filter(published=True)

    def get_context_data(self, **kwargs):
        context = super(PageView, self).get_context_data( **kwargs)
        context['header_image'] = context[self.context_object_name].image
        return context

class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('articles:list')
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleDeleteView, self).get_context_data( **kwargs)

        context['header_image'] = context[self.context_object_name].image
        return context

class ArticleListView(ListView):
    model = Article
    template_name = 'articles/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = super(ArticleListView, self).get_queryset()

        return queryset.filter(is_page=False).filter(published=True)

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        page = Article.objects.filter(slug='articles').filter(published=True).filter(is_page=True)
        if len(page) > 0:
             context['page'] = page[0]
             context['header_image'] = page[0].image

        logger.warn("Horribly inefficient query here")
        pt = cache.get('popular_tags')
        if pt is None:
            pt = []
            for tag in ArticleTag.objects.all():
                pt.append({
                    'tag': tag,
                    'count': tag.article_set.count()
                    })
            cache.set('popular_tags', pt, 3600)
        context['popular_tags'] = pt

        return context

class PageListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'articles/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = super(PageListView, self).get_queryset()

        return queryset.filter(is_page=True)

class HomePageView(ListView):
    model = Article
    template_name = 'home.html'
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = super(HomePageView, self).get_queryset()

        return queryset.filter(is_page=False).filter(published=True)[:5]

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        home_article = Article.objects.filter(slug='home').filter(published=True).filter(is_page=True)
        if len(home_article) > 0:
            context['home_article'] = home_article[0]
            context['header_image'] = home_article[0].image

        return context

class ArticleImageCreateView(LoginRequiredMixin, CreateView):
    model = ArticleImage
    template_name = 'articles/article_image_form.html'
    fields = ['image', 'title', 'article']

class ArticleImageUpdateView(LoginRequiredMixin, UpdateView):
    model = ArticleImage
    template_name = 'articles/article_image_form.html'
    fields = ['title']
    context_object_name = 'image'

    def get_context_data(self, **kwargs):
        context = super(ArticleImageUpdateView, self).get_context_data(**kwargs)
        context['header_image'] = context[self.context_object_name].image
        return context

class ArticleImageListView(LoginRequiredMixin, ListView):
    model = ArticleImage
    template_name = 'articles/article_image_list.html'
    context_object_name = 'images'

    def get_queryset(self):
        queryset = super(ArticleImageListView, self).get_queryset()

        return queryset.order_by('-pk')

class ArticleImageView(DetailView):
    template_name = 'articles/article_image.html'
    model = ArticleImage
    context_object_name = 'image'

class ArticleImageDeleteView(LoginRequiredMixin, DeleteView):
    model = ArticleImage
    success_url = reverse_lazy('articles:image-list')
    context_object_name = 'image'

    def get_context_data(self, **kwargs):
        context = super(ArticleImageDeleteView, self).get_context_data( **kwargs)

        context['header_image'] = context[self.context_object_name].image
        return context

class ArticleTagView(ListView):
    model = Article
    template_name = 'articles/tag.html'
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = super(ArticleTagView, self).get_queryset()
        return queryset.filter(tags__slug=self.kwargs['slug']).filter(is_page=False).filter(published=True)

templates/articles/article.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% load article_tags %}

{% block extrahead %}
<meta property="og:title" content="{{ article.title }}" />
<meta property="og:type" content="article" />
<meta property="og:article:author" content="{{ article.author }}" />
{% if article.tags %}
  {% for tag in article.tags.all %}
<meta property="og:article:tag" content="{{ tag.title }}" />
  {% endfor %}
{% endif %}
{% endblock %}

{% block title %}{{ article.title }}{% endblock %}
{% block page_title %}{{ article.title }}{% endblock %}
{% if article.subheading %}
{% block page_subheading %}{{ article.subheading }}{% endblock %}
{% endif %}
{% block extra_heading %}<span class="meta">Posted by {{ article.author }} on {{ article.created |date:'D j N Y' }}</span>{% endblock %}

{% block content %}
<div class="col-lg-2 col-md-1">
  {% if not user.is_anonymous and user == article.author %}
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="{% url 'articles:view' article.slug %}">View</a></li>
    <li><a href="{% url 'articles:edit' article.slug %}">Edit</a></li>
    <li><a href="{% url 'articles:new' %}">New</a></li>
    <li><a href="{% url 'articles:delete' article.slug %}">Delete</a></li>
  </ul>
  {% endif %}
</div>
<div class="col-lg-8 col-md-10 body">
  {{ body |markdown }}
</div>
{% if article.tags %}
<div class="col-lg-2 col-md-1">
  {% tag_list article.tags %}
</div>
{% endif %}
{% if DISQUS_SHORTNAME %}
  {% include "articles/disqus.html" with disqus_shortname="DISQUS_SHORTNAME" %}
{% endif %}
{% endblock %}

templates/articles/article_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Delete{% endblock %}
{% block page_title %}Delete permanently?{% endblock %}
{% if article.subheading %}
  {% block page_subheading %}{{ article.subheading }}{% endblock %}
{% endif %}
{% block extra_heading %}<span class="meta">Posted by <a href="#">{{ article.author }}</a> on {{ article.created }}</span>{% endblock %}


{% block content %}
<div class="col-lg-2 col-md-1">
  <ul class="nav nav-pills nav-stacked">
    <li><a href="{% url 'articles:view' article.slug %}">View</a></li>
    <li><a href="{% url 'articles:edit' article.slug %}">Edit</a></li>
    <li><a href="{% url 'articles:new' %}">New</a></li>
    <li class="active"><a href="{% url 'articles:delete' article.slug %}">Delete</a></li>
  </ul>
</div>
<div class="col-lg-8 col-md-10 body">
  <form class="form" action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.title }}"?</p>
    <a href="{% url 'articles:view' object.slug %}" class="btn"> Cancel </a>
    <button type="submit" class="btn btn-primary btn-danger">
      {% bootstrap_icon "remove" %} Delete
    </button>
  </form>
</div>
{% endblock %}

templates/articles/article_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}{% if article %}Edit {{ article.title }}{% else %}New article{% endif %}{% endblock %}
{% block page_title %}{% if article %}{{ article.title }}{% else %}New article{% endif %}{% endblock %}
{% if article %}
	{% if article.subheading %}
	{% block page_subheading %}{{ article.subheading }}{% endblock %}
	{% endif %}
	{% block extra_heading %}<span class="meta">Posted by <a href="#">{{ article.author }}</a> on {{ article.created }}</span>{% endblock %}
{% endif %}

{% block content %}
<div class="col-lg-2 col-md-1">
  <ul class="nav nav-pills nav-stacked">
    {% if article %}
    <li><a href="{% url 'articles:view' article.slug %}">View</a></li>
    <li class="active"><a href="{% url 'articles:edit' article.slug %}">Edit</a></li>
    <li><a href="{% url 'articles:delete' article.slug %}">Delete</a></li>
    {% else %}
    <li class="active"><a href="{% url 'articles:new' %}">New</a></li>
    {% endif %}
  </ul>
</div>
<div class="col-lg-8 col-md-10 body">
    <span>The page that has the slug of 'home' will be the home page.</span>
	{{ form.errors }}
	<form role="form" method="post" enctype="multipart/form-data" action="{% if article %}{% url 'articles:edit' article.slug %}{% else %}{% url 'articles:new' %}{% endif %}">{% csrf_token %}
	  {% bootstrap_form form layout='inline' %}
	  {% buttons %}
	    {% if article %}
	    <a href="{% url 'articles:view' article.slug %}" class="btn"> Cancel </a>
	    {% else %}
	    <a href="{% url 'articles:list' %}" class="btn"> Cancel </a>
	    {% endif %}
	    <button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "ok" %} Submit
	    </button>
	  {% endbuttons %}
	</form>
</div>
{% endblock %}

templates/articles/article_image.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block title %}{{ image.title }}{% endblock %}
{% block page_title %}{{ image.title }}{% endblock %}
{% block extra_heading %}<span class="meta">Posted on {{ image.created }}</span>{% endblock %}

{% block content %}
<div class="col-lg-2 col-md-1">
  {% if user %}
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="{% url 'articles:image-view' image.pk %}">View</a></li>
    <li><a href="{% url 'articles:image-edit' image.pk %}">Edit</a></li>
    <li><a href="{% url 'articles:image-delete' image.pk %}">Delete</a></li>
    <li><a href="{% url 'articles:image-list' %}">List</a></li>
    <li><a href="{% url 'articles:image-new' %}">New</a></li>
  </ul>
  {% endif %}
</div>
<div class="col-lg-8 col-md-10 body">
  <img src="{{ image.image.url }}">
  <h2>{{ image.title }}</h2>
  <p>ID: {{ image.pk }}</p>
</div>
{% endblock %}

templates/articles/article_image_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}{% if article %}Edit {{ article.title }}{% else %}New article{% endif %}{% endblock %}
{% block page_title %}{% if article %}{{ article.title }}{% else %}New article{% endif %}{% endblock %}
{% if article %}
	{% if article.subheading %}
	{% block page_subheading %}{{ article.subheading }}{% endblock %}
	{% endif %}
	{% block extra_heading %}<span class="meta">Posted on {{ article.created }}</span>{% endblock %}
{% endif %}

{% block content %}
<div class="col-lg-2 col-md-1">
  {% if user %}
  <ul class="nav nav-pills nav-stacked">
  	{% if image %}
    <li><a href="{% url 'articles:image-view' image.pk %}">View</a></li>
    <li class="active"><a href="{% url 'articles:image-edit' image.pk %}">Edit</a></li>
    <li><a href="{% url 'articles:image-delete' image.pk %}">Delete</a></li>
    {% endif %}
    <li{% if not image %} class="active"{% endif %}><a href="{% url 'articles:image-new' %}">New</a></li>
    <li><a href="{% url 'articles:image-list' %}">List</a></li>
  </ul>
  {% endif %}
</div>

<div class="col-lg-8 col-md-10 body">
	{{ form.errors }}
	<form role="form" method="post" enctype="multipart/form-data" action="{% if object %}{% url 'articles:image-edit' object.pk %}{% else %}{% url 'articles:image-new' %}{% endif %}">{% csrf_token %}
	  {% bootstrap_form form layout='inline' %}
	  {% buttons %}
	    {% if object %}
	    <a href="{% url 'articles:image-view' object.pk %}" class="btn"> Cancel </a>
	    {% else %}
	    <a href="{% url 'articles:list' %}" class="btn"> Cancel </a>
	    {% endif %}
	    <button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "ok" %} Submit
	    </button>
	  {% endbuttons %}
	</form>
</div>
{% endblock %}

templates/articles/article_image_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load markdown_deux_tags %}

{% block title %}Article images{% endblock %}
{% block page_title %}Article images{% endblock %}
{% block page_subheading %}{% endblock %}
{% block extra_heading %}{% endblock %}

{% block content %}
<div class="col-lg-2 col-md-1">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="{% url 'articles:image-list' %}">List</a></li>
    <li><a href="{% url 'articles:image-new' %}">New</a></li>
  </ul>
</div>
{% if object_list %}
<div class="col-lg-8 col-md-10">
  {% for image in object_list %}
    <div class="post-preview">
      <a href="{% url 'articles:image-view' image.pk %}" class="">
        <div class="col-lg-4 col-md-4">
          <img src="{% thumbnail image.image "200x200" as im %}{{ im.url }}{% endthumbnail %}">
        </div>
        <div class=" col-lg-8 col-md-6">
          <h2 class="post-title">
            {{ image.pk }} - {{ image.title }}
          </h2>
          <p class="post-meta col-lg-12 col-md-12">Posted by <a href="#">{{ image.author }}</a> on {{ image.created }}</p>
        </div>
      </a>
    </div>
    <hr>
  {% empty %}
    <p>No images</p>
  {% endfor %}
</div>
{% endif %}
{% endblock %}

templates/articles/articleimage_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Delete{% endblock %}
{% block page_title %}Delete permanently?{% endblock %}
{% block extra_heading %}<span class="meta">Posted on {{ image.created }}</span>{% endblock %}


{% block content %}
<div class="col-lg-2 col-md-1">
  <ul class="nav nav-pills nav-stacked">
    <li><a href="{% url 'articles:image-view' image.pk %}">View</a></li>
    <li><a href="{% url 'articles:image-edit' image.pk %}">Edit</a></li>
    <li class="active"><a href="{% url 'articles:image-delete' image.pk %}">Delete</a></li>
    <li><a href="{% url 'articles:image-new' %}">New</a></li>
    <li><a href="{% url 'articles:image-list' %}">List</a></li>
  </ul>
</div>
<div class="col-lg-8 col-md-10 body">
  <form class="form" action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ image.title }}"?</p>
    <a href="{% url 'articles:image-view' image.pk %}" class="btn"> Cancel </a>
    <button type="submit" class="btn btn-primary btn-danger">
      {% bootstrap_icon "remove" %} Delete
    </button>
  </form>
</div>
{% endblock %}

templates/articles/disqus.html
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = '{{ DISQUS_SHORTNAME }}';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

templates/articles/page.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block title %}{{ page.title }}{% endblock %}
{% block page_title %}{{ page.title }}{% endblock %}

{% if page.image %}
  {% block header_image %}{{ page.image.url }}{% endblock %}
{% endif %}

{% block content %}
<div class="col-lg-2 col-md-2">
  {% if user == page.author %}
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="{% url 'articles:view' page.slug %}">View</a></li>
    <li><a href="{% url 'articles:edit' page.slug %}">Edit</a></li>
    <li><a href="{% url 'articles:delete' page.slug %}">Delete</a></li>
  </ul>
  {% endif %}
</div>
<div class="col-lg-8 col-md-8 body">
  {{ page.body |markdown }}
</div>
{% endblock %}