accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views
from django.conf import settings
import accounts.views


urlpatterns = [
    url(r'^$',                        accounts.views.redirect_view,        name='redirect'),
    url(r'^profile',                accounts.views.profile,        name='profile'),
    url(r'^user/(?P<username>[a-z]{2,8})$', accounts.views.public_profile, name='public_profile'),
    # url(r'^register$',            accounts.views.register,       name='register'),


    url(r'^login/$',                views.LoginView.as_view(),                   name='login'),
    url(r'^logout$',                views.LogoutView.as_view(),                  name='logout'),
    url(r'^password_change/$',      views.PasswordChangeView.as_view(),         name='password_change'),
    url(r'^password_change/done/$', views.PasswordChangeDoneView.as_view(),    name='password_change_done'),
    url(r'^password_reset/$',       views.PasswordResetView.as_view(),          name='password_reset'),
    url(r'^password_reset/done/$',  views.PasswordResetDoneView.as_view(),     name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        views.PasswordResetConfirmView.as_view(),  name='password_reset_confirm'),
    url(r'^reset/done/$',           views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.ALLOW_REGISTRATION:
    urlpatterns = urlpatterns + [url(r'^register$', accounts.views.register, name='register')]

articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',                                   views.ArticleListView.as_view(), name='list'),
    path('new',                                views.ArticleCreateView.as_view(),  name='new'),
    path('pages/<slug:slug>',                  views.PageView.as_view(), name='page-view'),
    path('pages/',                            views.PageListView.as_view(), name='page-view'),
    path('images/',                           views.ArticleImageListView.as_view(), name='image-list'),
    path('images/new',                        views.ArticleImageCreateView.as_view(), name='image-new'),
    path('images/<int:pk>',             views.ArticleImageView.as_view(), name='image-view'),
    path('images/<int:pk>/edit',        views.ArticleImageUpdateView.as_view(), name='image-edit'),
    path('images/<int:pk>/delete',      views.ArticleImageDeleteView.as_view(), name='image-delete'),

    path('tags/<slug:slug>',        views.ArticleTagView.as_view(), name='tag-view'),

    path('<slug:slug>',             views.ArticleView.as_view(), name='view'),
    path('<slug:slug>/edit',        views.ArticleUpdateView.as_view(), name='edit'),
    path('<slug:slug>/delete',      views.ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from articles.views import PageView, HomePageView, PageListView
admin.autodiscover()

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),

    # Authentication
    # url('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # path('articles/', include('articles.urls')),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url('admin/doc/', include('django.contrib.admindocs.urls')),
    path('search', include(('search.urls', 'search'), namespace='search')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    path('pages/', PageListView.as_view(), name='page-list-view'),
    path('<slug:slug>', PageView.as_view(), name='page-view'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

search/urls.py
from django.urls import path
from . import views
from haystack.views import SearchView
from django.conf.urls import url

urlpatterns = [
    path('', views.SiteSearchView.as_view(), name="haystack_search"),
]

templates/base.html
{% load static %}
{% load thumbnail %}
{% load bootstrap3 %}
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% if GOOGLE_SITE_VERIFICATION %}
    <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION }}">
    {% endif %}
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static "css/clean-blog.min.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    {% comment %}
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    {% endcomment %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extrahead %}{% endblock %}
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">{{ SITE_NAME }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li><a href="{% url 'search:haystack_search' %}">Search</a></li>
            <li><a href="{% url 'articles:list' %}">Articles</a></li>
            {% for p in menu_pages %}
            <li><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></li>
            {% endfor %}
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:profile' %}">{{ user.username }}</a></li>
            <li><a href="{% url 'articles:new' %}">New article</a></li>
            <li><a href="{% url 'accounts:logout' %}">Sign out</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Sign in</a></li>
            {% endif %}
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ),
    {% if header_image %}{% thumbnail header_image "1900x492" as im %}url('{{ im.url }}'){% endthumbnail %}
    {% else %}url('{% static "img/home-bg.jpg" %}'){% endif %}">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="{% if homepage or not article %}site{% else %}post{% endif %}-heading">
              <h1>{% block page_title %}{% endblock %}</h1>
              {% if not article and article.is_page %}
              <hr class="small">
              {% endif %}
              <span class="subheading">{% block page_subheading %}{% endblock %}</span>
              <span class="meta">{% block extra_heading %}{% endblock %}</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Main Content -->
    {% if messages %}
    <div class="container">
      {% bootstrap_messages %}
    </div>
    {% endif %}
    <div class="container">
      <div id="content" class="row">{% block content %}{% endblock %}</div>
    </div>
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
            <!--
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            -->
              <li>
                <a href="https://www.drupal.org/u/tobyontour">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-drupal fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/tobyontour">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">{{ SITE_COPYRIGHT |safe}}</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- end -->
    <!-- Custom Theme JavaScript -->
    <!--<script src="{% static "js/clean-blog.min.js" %}"></script>-->
    {% block script %}{% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% load thumbnail %}

{% block title %}Toby's website{% endblock %}
{% block page_title %}{% endblock %}
{% block page_subheading %}{{ home_article.subheading }}{% endblock %}

{% block content %}
{% if home_article %}
  <div class="col-lg-2 col-md-1 col-sm-1">
  {% if user == home_article.author %}
    <ul class="nav nav-pills nav-stacked">
      {#<li class="active"><a href="{% url 'articles:view' home_article.slug %}">View</a></li>#}
      <li><a href="{% url 'articles:edit' home_article.slug %}">Edit</a></li>
      <li><a href="{% url 'articles:delete' home_article.slug %}">Delete</a></li>
    </ul>
  {% endif %}
  </div>
  <div class="col-lg-8 col-md-10 col-sm-10">
    {#<div class="visible-xs">XS</div> <div class="visible-sm">SM</div> <div class="visible-md">MD</div> <div class="visible-lg">LG</div>#}
    <div class="body">{{ home_article.body | markdown }}</div>
  </div>
</div>
<hr>
{% endif %}
<div class="row">
  <div class="col-lg-2 col-md-1"></div>
  {% for article in articles|slice:":2" %}
  <div class="col-lg-4 col-md-5 col-md-offset-0 col-sm-10 col-sm-offset-1">
    <div class="post-preview">
      {% thumbnail article.image "600x200" crop="center" as im %}<img src="{{ im.url }}">{% endthumbnail %}
      <a href="{% url 'articles:view' article.slug %}">
        <h3 class="post-title">
          {{ article.title }}
        </h3>
        {% if article.subheading %}
        <em class="post-subtitle">
          {{ article.subheading }}
        </em>
        {% endif %}
      </a>
      <p class="post-meta">Posted by <a href="#">{{ article.author }}</a> on {{ article.created }}</p>
      <div class="body">{{ article.body | markdown | truncatewords_html:20 }}</div>
    </div>
  </div>
  {% endfor %}
</div>
<hr>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-offset-1 col-sm-10">
    <div class="row">
      {% for article in articles|slice:"2:" %}
      <div class="col-sm-4">
        <div class="post-preview">
          {# {% thumbnail article.image "455x200" crop="center" as im %}<img src="{{ im.url }}">{% endthumbnail %} #}
          <a href="{% url 'articles:view' article.slug %}">

            <h4 class="post-title visible-lg">{{ article.title }}</h4>
            <h4 class="post-title visible-md visible-sm visible-xs" style="font-size: 110%">{{ article.title }}</h4>
            {% if article.subheading %}
            <em class="post-subtitle">{{ article.subheading }}</em>
            {% endif %}
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div class="row">
<hr>
<!-- Pager -->
<ul class="pager">
    <li class="next">
        <a href="{% url 'articles:list' %}">Older Posts &rarr;</a>
    </li>
</ul>
{% endblock %}